# Generated by Django 5.1.7 on 2025-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UzumbankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('service_id', models.BigIntegerField()),
                ('trans_id', models.UUIDField(unique=True)),
                ('timestamp', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], max_length=20)),
                ('trans_time', models.BigIntegerField(blank=True, null=True)),
                ('confirm_time', models.BigIntegerField(blank=True, null=True)),
                ('reverse_time', models.BigIntegerField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'uzumbank_transaction',
            },
        ),
    ]
